version: '2'
services:
   api:
      container_name: api
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
      - "11080:8080"
      environment:
      - API_ENCODING_KEY=${API_ENCODING_KEY}
      - ENV API_MAX_UPLOAD_SIZE_KB=16384      
      - API_CONNECTION_STRING=jdbc:mysql://api-db:3306/hutoma?user=hutoma_caller&password=>YR"khuN*.gF)V4#&zeroDateTimeBehavior=convertToNull
      - API_DBCONNECTIONPOOL_MIN_SIZE=8
      - API_DBCONNECTIONPOOL_MAX_SIZE=64
      - API_RATELIMIT_CHAT_BURST=3.0
      - API_RATELIMIT_CHAT_FREQUENCY=2.0
      - API_RATELIMIT_QUICKREAD_BURST=7.0
      - API_RATELIMIT_QUICKREAD_FREQUENCY=0.5
      - API_RATELIMIT_LOADTEST_BURST=32768.0
      - API_RATELIMIT_LOADTEST_FREQUENCY=8192.5
#      - API_AI_WNET_ENDPOINT=http://ai-wnet:8888/ai
#      - API_AI_RNN_ENDPOINT=http://ai-rnn:8889/ai
      - API_AI_WNET_ENDPOINT=http://10.132.0.5:8888/ai
      - API_AI_RNN_ENDPOINT=http://10.3.0.161:8889/ai
      - API_AI_AIML_ENDPOINT=http://ai-aiml:8080/ai
      - API_LOGGING_URL=http://log-svc:8080/log
      - API_LOGGING_CADENCY=5000
networks:
  default:
    external:
      name: internal_net
