version: '2'
services:
   api:
      container_name: api
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
      - "11080:8080"
      environment:
      - API_ENCODING_KEY=${API_ENCODING_KEY}
      - API_MAX_UPLOAD_SIZE_KB=16384
      - API_CONNECTION_STRING=jdbc:mysql://api-db:3306/hutoma?user=hutoma_caller&password=>YR"khuN*.gF)V4#&zeroDateTimeBehavior=convertToNull
      - API_DBCONNECTIONPOOL_MIN_SIZE=8
      - API_DBCONNECTIONPOOL_MAX_SIZE=64
      - API_RATELIMIT_CHAT_BURST=3.0
      - API_RATELIMIT_CHAT_FREQUENCY=2.0
      - API_RATELIMIT_QUICKREAD_BURST=7.0
      - API_RATELIMIT_QUICKREAD_FREQUENCY=0.5
      - API_RATELIMIT_LOADTEST_BURST=32768.0
      - API_RATELIMIT_LOADTEST_FREQUENCY=8192.5
      - API_BACKEND_REQUEST_TIMEOUT_MS=20000
      - API_LOGGING_URL=http://log-svc:8080/log
      - API_LOGGING_CADENCY=5000
      - API_AI_AIML_BOT_AIIDS=e1bb8226-e8ce-467a-8305-bc2fcb89dd7f,491091b1-5458-4d87-b7e9-0ccf3002970c,9a7a3376-e872-463e-aaa5-9f7e0e8c3380,873e61b9-9b75-449b-9532-821fcea6f864
networks:
  default:
    external:
      name: internal_net
