CREATE DATABASE  IF NOT EXISTS `django` CHARACTER SET utf8mb4;
USE `django`;

# Privileges for `django_caller`@`%`
GRANT USAGE ON *.* TO 'django_caller'@'%' IDENTIFIED BY PASSWORD '*43AB6D5047308CDDD3C9C7BF244A184EB22559E2';
GRANT CREATE, ALTER, EXECUTE, INSERT, SELECT, DELETE, UPDATE, REFERENCES, INDEX ON `django`.* TO 'django_caller'@'%';
